### ISSUE TITLE
High CPU usage on fast scrolling on bigger lists?

### ISSUE THREAD

**Issue by JamesHealdUK** [mischa-hildebrand/AlignedCollectionViewFlowLayout#4]
Loving the library! So useful, its suprising that UICollectionView doesnt support this kind of functionality by default.

Just been testing it myself by using the `AlignedCollectionViewFlowLayout` example to test the performance. Only thing is, if I have a list of items around 500 long, I notice that the CPU usage jumps to up to 80% if you can scroll fast enough. This will happen regardless of the arrays size but is more difficult to replicate because you cant scroll as fast.

Is there anything I can do t improve the performance? This is using the iPhone Simulator on iOS 10.3. I know that the iOS Simulator isnt very good for judging performance so maybe its just that.

**Comment by mischa-hildebrand** [comment]
Yes, I've been wondering myself for a long time why `UICollectionViewFlowLayout` doesn't provide alignment options by default. It's nothing fancy but it's rather tricky to add it on top of an existing layout.

Performance definitely _is_ an issue with `AlignedCollectionViewFlowLayout`. That's why I added the note in the `README.md` file:

> ### ℹ️ Important:
> 
> `AlignedCollectionViewFlowLayout` was developed with a "**tag view**" in mind, i.e. a collection view that displays a limited number of items with a relatively simple layout. It works perfectly for this use case. While it also does its job for a large number of items and more complex cell layouts **scrolling might become laggy** in this case. **This is due to the fact the layout needs to recursively obtain layout attributes from its superclass and cannot be avoided.** If you experience unacceptable lagginess please consider other alternatives.

The important sentence here is the second last. In my opinion, it is not possible to drastically improve performance with the approach I used (retrieving and modifying the layout attributes from the superclass) without making any additional assumptions about the specific use case or the implementation of `UICollectionViewFlowLayout`.

In the discussion of the [pull request for adding the center alignment option](https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout/pull/2) [@Pheltas](https://github.com/Phelthas) has suggested to implement a cache for the layout attributes. However, the cache would have to be computed upfront so if you have hundreds or thousands of collection view items you'll freeze your UI at the beginning until the initial computation and caching is done. Please see the [discussion](https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout/pull/2) for details.

I'm always open for alternative solutions in case I have overlooked something. But for now I suggest to go with my recommendation and use `AlignedCollectionViewFlowLayout` only for "tag views" or similar things, i.e. collection views with 20-30 items, for example.
